version: "3"
services: 
  node:
    restart: always
    depends_on: 
      - mysql
      - redis
    build: ./node
    expose: 
      - "3000"
    ports: 
      - "3001:3000"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/node/app:/home/node/app"
      - "./Data/python/images:/home/node/app/public/images"

  alipay:
    restart: always
    build: ./node
    expose: 
      - "3000"
    ports: 
      - "3002:3000"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/node/alipay:/home/node/app"

  mysql:
    image: mysql
    expose: 
      - "3306"
    ports: 
      - "3308:3306"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/mysql:/var/lib/mysql"

  redis:
    image: redis
    expose: 
      - "6379"
    networks: 
      - "proxy"
      
  python:
    depends_on: 
      - mysql
    build: ./py
    expose: 
      - "8080"
    ports: 
      - "3003:8080"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/python:/usr/src/app"
    restart: always
    logging:
      options: 
        max-size: "10k"

networks: 
  proxy:
    driver: bridge


