version: "3"
services: 
  node:
    restart: always
    depends_on: 
      - mysql
      - redis
    build: ./node
    expose: 
      - "3000"
    ports: 
      - "3001:3000"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/node/app:/home/node/app"

  mysql:
    image: mysql
    expose: 
      - "3306"
    ports: 
      - "3308:3306"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/mysql:/var/lib/mysql"

  redis:
    image: redis
    expose: 
      - "6379"
    networks: 
      - "proxy"

networks: 
  proxy:
    driver: bridge


