version: "3"
services: 
  node:
    restart: always
    depends_on: 
      - mysql
      - redis
    build: ./app
    expose: 
      - "3000"
    ports: 
      - "3001:3000"
    networks: 
      - "proxy"
    volumes: 
      - "./python/images:/home/node/app/public/images"
    logging:
      options: 
        max-size: "10k"

  alipay:
    restart: always
    build: ./alipay
    expose: 
      - "3000"
    ports: 
      - "3002:3000"
    networks: 
      - "proxy"
    logging:
      options: 
        max-size: "10k"

  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - ./CarsData.sql:/docker-entrypoint-initdb.d/CarsData.sql
    networks: 
      - "proxy"

  redis:
    image: redis
    expose: 
      - "6379"
    networks: 
      - "proxy"
      
  python:
    restart: always
    depends_on: 
      - mysql
    build: ./python
    expose: 
      - "8080"
    ports: 
      - "3003:8080"
    networks: 
      - "proxy"
    volumes: 
      - "./python/images:/usr/src/app/images"
    logging:
      options: 
        max-size: "10k"

networks: 
  proxy:
    driver: bridge
