apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-parking-money-pic
  labels:
    alicloud-pvname: pv-parking-money-pic
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: oss
  csi:
    driver: ossplugin.csi.alibabacloud.com
    volumeHandle: pv-parking-money-pic
    nodePublishSecretRef:
      name: oss-secret
      namespace: default
    volumeAttributes:
      bucket: "parking-money-pic"
      url: "oss-cn-shenzhen.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"