apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-parking-money-pic
  labels:
    alicloud-pvname: pv-parking-money-pic
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ssd
  hostPath:
    path: /home/parking-money-pic
